# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Felipe\PycharmProjects\metacontrol\gui\views\ui_files\caballerotab.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1024, 720)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMaximumSize(QtCore.QSize(350, 16777215))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 0, 0, 1, 1)
        self.startOptPushButton = QtWidgets.QPushButton(self.groupBox_3)
        self.startOptPushButton.setObjectName("startOptPushButton")
        self.gridLayout_3.addWidget(self.startOptPushButton, 1, 0, 1, 1)
        self.abortOptPushButton = QtWidgets.QPushButton(self.groupBox_3)
        self.abortOptPushButton.setObjectName("abortOptPushButton")
        self.gridLayout_3.addWidget(self.abortOptPushButton, 2, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_3, 4, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setMaximumSize(QtCore.QSize(350, 16777215))
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tabWidget = QtWidgets.QTabWidget(self.groupBox_5)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.formLayout_2 = QtWidgets.QFormLayout(self.tab)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_17 = QtWidgets.QLabel(self.tab)
        self.label_17.setObjectName("label_17")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.ipoptAddressLineEdit = QtWidgets.QLineEdit(self.tab)
        self.ipoptAddressLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.ipoptAddressLineEdit.setObjectName("ipoptAddressLineEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ipoptAddressLineEdit)
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setObjectName("label_13")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.ipoptMaxIterLineEdit = QtWidgets.QLineEdit(self.tab)
        self.ipoptMaxIterLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.ipoptMaxIterLineEdit.setObjectName("ipoptMaxIterLineEdit")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.ipoptMaxIterLineEdit)
        self.label_14 = QtWidgets.QLabel(self.tab)
        self.label_14.setObjectName("label_14")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.ipoptConTolLineEdit = QtWidgets.QLineEdit(self.tab)
        self.ipoptConTolLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.ipoptConTolLineEdit.setObjectName("ipoptConTolLineEdit")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.ipoptConTolLineEdit)
        self.label_16 = QtWidgets.QLabel(self.tab)
        self.label_16.setObjectName("label_16")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.ipoptDualFeasLineEdit = QtWidgets.QLineEdit(self.tab)
        self.ipoptDualFeasLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.ipoptDualFeasLineEdit.setObjectName("ipoptDualFeasLineEdit")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.ipoptDualFeasLineEdit)
        self.ipoptTestConnectionPushButton = QtWidgets.QPushButton(self.tab)
        self.ipoptTestConnectionPushButton.setObjectName("ipoptTestConnectionPushButton")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.ipoptTestConnectionPushButton)
        self.tabWidget.addTab(self.tab, "")
        self.gridLayout_5.addWidget(self.tabWidget, 2, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_5.addWidget(self.label_12, 0, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.groupBox_5)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_5.addWidget(self.comboBox, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_5, 3, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMaximumSize(QtCore.QSize(350, 16777215))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.firstFactorLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.firstFactorLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.firstFactorLineEdit.setObjectName("firstFactorLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.firstFactorLineEdit)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.secondFactorLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.secondFactorLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.secondFactorLineEdit.setObjectName("secondFactorLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.secondFactorLineEdit)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.tolContractLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.tolContractLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.tolContractLineEdit.setObjectName("tolContractLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.tolContractLineEdit)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.conTolLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.conTolLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.conTolLineEdit.setObjectName("conTolLineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.conTolLineEdit)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.penaltyFactorLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.penaltyFactorLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.penaltyFactorLineEdit.setObjectName("penaltyFactorLineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.penaltyFactorLineEdit)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.tol1LineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.tol1LineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.tol1LineEdit.setObjectName("tol1LineEdit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.tol1LineEdit)
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.tol2LineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.tol2LineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.tol2LineEdit.setObjectName("tol2LineEdit")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.tol2LineEdit)
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.maxFunEvalsLineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.maxFunEvalsLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.maxFunEvalsLineEdit.setObjectName("maxFunEvalsLineEdit")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.maxFunEvalsLineEdit)
        self.label_18 = QtWidgets.QLabel(self.groupBox_2)
        self.label_18.setObjectName("label_18")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.regrpolyComboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.regrpolyComboBox.setObjectName("regrpolyComboBox")
        self.regrpolyComboBox.addItem("")
        self.regrpolyComboBox.addItem("")
        self.regrpolyComboBox.addItem("")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.regrpolyComboBox)
        self.gridLayout_2.addWidget(self.groupBox_2, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.gridLayout_2.addItem(spacerItem, 5, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(350, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 1, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.controlPanelTextBrowser = QtWidgets.QTextBrowser(self.groupBox_4)
        self.controlPanelTextBrowser.setObjectName("controlPanelTextBrowser")
        self.gridLayout_4.addWidget(self.controlPanelTextBrowser, 1, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_4, 1, 1, 3, 2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 2, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_15 = QtWidgets.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout_6.addWidget(self.label_15, 0, 0, 1, 1)
        self.resultsTableWidget = QtWidgets.QTableWidget(self.groupBox_6)
        self.resultsTableWidget.setObjectName("resultsTableWidget")
        self.resultsTableWidget.setColumnCount(0)
        self.resultsTableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.resultsTableWidget.setVerticalHeaderItem(0, item)
        self.gridLayout_6.addWidget(self.resultsTableWidget, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_6, 4, 1, 2, 2)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        self.comboBox.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_9.setText(_translate("Form", "Perform optimization"))
        self.startOptPushButton.setText(_translate("Form", "Start"))
        self.abortOptPushButton.setText(_translate("Form", "Abort"))
        self.label_17.setText(_translate("Form", "Server address:"))
        self.ipoptAddressLineEdit.setText(_translate("Form", "http://localhost:5000"))
        self.label_13.setText(_translate("Form", "Maximum number of iterations:"))
        self.ipoptMaxIterLineEdit.setText(_translate("Form", "3000"))
        self.label_14.setText(_translate("Form", "Constraint tolerance:"))
        self.ipoptConTolLineEdit.setText(_translate("Form", "1e-6"))
        self.label_16.setText(_translate("Form", "Dual feasibility tolerance:"))
        self.ipoptDualFeasLineEdit.setText(_translate("Form", "1e-8"))
        self.ipoptTestConnectionPushButton.setText(_translate("Form", "Test server connection"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "IpOpt"))
        self.label_12.setText(_translate("Form", "NLP solvers options"))
        self.comboBox.setItemText(0, _translate("Form", "Choose NLP solver"))
        self.comboBox.setItemText(1, _translate("Form", "IpOpt (server)"))
        self.label_2.setText(_translate("Form", "First contraction factor:"))
        self.firstFactorLineEdit.setText(_translate("Form", "0.8"))
        self.label_3.setText(_translate("Form", "Second contraction factor:"))
        self.secondFactorLineEdit.setText(_translate("Form", "0.4"))
        self.label_4.setText(_translate("Form", "Maximum contraction tolerance:"))
        self.tolContractLineEdit.setText(_translate("Form", "1e-4"))
        self.label_5.setText(_translate("Form", "Feasibility (constraint) tolerance:"))
        self.conTolLineEdit.setText(_translate("Form", "1e-6"))
        self.label_6.setText(_translate("Form", "Penalty factor:"))
        self.penaltyFactorLineEdit.setText(_translate("Form", "200"))
        self.label_7.setText(_translate("Form", "Refinement tolerance:"))
        self.tol1LineEdit.setText(_translate("Form", "1e-6"))
        self.label_8.setText(_translate("Form", "Termination tolerance:"))
        self.tol2LineEdit.setText(_translate("Form", "1e-7"))
        self.label_11.setText(_translate("Form", "Maximum function evaluations:"))
        self.maxFunEvalsLineEdit.setText(_translate("Form", "4000"))
        self.label_18.setText(_translate("Form", "Regression model:"))
        self.regrpolyComboBox.setItemText(0, _translate("Form", "poly0"))
        self.regrpolyComboBox.setItemText(1, _translate("Form", "poly1"))
        self.regrpolyComboBox.setItemText(2, _translate("Form", "poly2"))
        self.label.setText(_translate("Form", "Adaptive sampling setup"))
        self.label_10.setText(_translate("Form", "Control panel"))
        self.label_15.setText(_translate("Form", "Results"))
        item = self.resultsTableWidget.verticalHeaderItem(0)
        item.setText(_translate("Form", "Values"))

