# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Felipe\PycharmProjects\metacontrol\gui\views\ui_files\metamodeltab.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1043, 814)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setStyleSheet("QGroupBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 9px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 10px;\n"
"    top: 5px;\n"
"    padding: 0 3px 0 3px;\n"
"}")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem, 8, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 1, 0, 1, 1)
        self.thetaTableWidget = QtWidgets.QTableWidget(self.groupBox)
        self.thetaTableWidget.setMaximumSize(QtCore.QSize(16777215, 300))
        self.thetaTableWidget.setObjectName("thetaTableWidget")
        self.thetaTableWidget.setColumnCount(4)
        self.thetaTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.thetaTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.thetaTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.thetaTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.thetaTableWidget.setHorizontalHeaderItem(3, item)
        self.thetaTableWidget.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_2.addWidget(self.thetaTableWidget, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem1, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem2, 4, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 0, 0, 1, 1)
        self.generateModelpushButton = QtWidgets.QPushButton(self.groupBox_3)
        self.generateModelpushButton.setObjectName("generateModelpushButton")
        self.gridLayout_4.addWidget(self.generateModelpushButton, 1, 0, 1, 1)
        self.viewPlotPushButton = QtWidgets.QPushButton(self.groupBox_3)
        self.viewPlotPushButton.setEnabled(False)
        self.viewPlotPushButton.setObjectName("viewPlotPushButton")
        self.gridLayout_4.addWidget(self.viewPlotPushButton, 1, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_3, 9, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem3 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem3, 4, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.regrComboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.regrComboBox.setObjectName("regrComboBox")
        self.regrComboBox.addItem("")
        self.regrComboBox.addItem("")
        self.regrComboBox.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.regrComboBox)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.corrComboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.corrComboBox.setObjectName("corrComboBox")
        self.corrComboBox.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.corrComboBox)
        self.gridLayout_3.addLayout(self.formLayout, 3, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 5, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_4.setStyleSheet("QGroupBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 9px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 10px;\n"
"    top: 5px;\n"
"    padding: 0 3px 0 3px;\n"
"}")
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 0, 0, 1, 5)
        self.trainingPointsLabel = QtWidgets.QLabel(self.groupBox_4)
        self.trainingPointsLabel.setObjectName("trainingPointsLabel")
        self.gridLayout_5.addWidget(self.trainingPointsLabel, 1, 1, 1, 1)
        self.validationPointsLabel = QtWidgets.QLabel(self.groupBox_4)
        self.validationPointsLabel.setObjectName("validationPointsLabel")
        self.gridLayout_5.addWidget(self.validationPointsLabel, 1, 4, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 1, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 1, 0, 1, 1)
        self.splitDataHorizontalSlider = QtWidgets.QSlider(self.groupBox_4)
        self.splitDataHorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.splitDataHorizontalSlider.setObjectName("splitDataHorizontalSlider")
        self.gridLayout_5.addWidget(self.splitDataHorizontalSlider, 1, 2, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_4, 7, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem4, 6, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.gridLayout_2.addItem(spacerItem5, 10, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "Metamodel Construction"))
        item = self.thetaTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Variables"))
        item = self.thetaTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Lower Bound"))
        item = self.thetaTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Upper Bound"))
        item = self.thetaTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Initial Estimate"))
        self.label.setText(_translate("Form", "Hyperparameters (theta) definition"))
        self.label_5.setText(_translate("Form", "Results generation and visualization"))
        self.generateModelpushButton.setText(_translate("Form", "Generate metamodel"))
        self.viewPlotPushButton.setText(_translate("Form", "View graphical results"))
        self.label_4.setText(_translate("Form", "Regression and Correlation (Kernel) model selection"))
        self.label_2.setText(_translate("Form", "Polynomial (regression) model:"))
        self.regrComboBox.setItemText(0, _translate("Form", "Constant (0th order)"))
        self.regrComboBox.setItemText(1, _translate("Form", "Linear (1st order)"))
        self.regrComboBox.setItemText(2, _translate("Form", "Quadratic (2nd order)"))
        self.label_3.setText(_translate("Form", "Correlation (kernel) model:"))
        self.corrComboBox.setItemText(0, _translate("Form", "Exponential Gaussian (Kriging)"))
        self.label_6.setText(_translate("Form", "Split data between training / validation (test) sets"))
        self.trainingPointsLabel.setText(_translate("Form", "0"))
        self.validationPointsLabel.setText(_translate("Form", "0"))
        self.label_8.setText(_translate("Form", "Validation points:"))
        self.label_7.setText(_translate("Form", "Training points:"))

