# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Felipe\PycharmProjects\metacontrol\gui\views\ui_files\redspacemetamodeldialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1025, 796)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setStyleSheet("QGroupBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 9px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 10px;\n"
"    top: 5px;\n"
"    padding: 0 3px 0 3px;\n"
"}")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem, 8, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem1, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem2, 4, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 1, 0, 1, 2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 6, 1, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_4.setStyleSheet("QGroupBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 9px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 10px;\n"
"    top: 5px;\n"
"    padding: 0 3px 0 3px;\n"
"}")
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem4 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem4, 4, 1, 1, 1)
        self.holdOutRadioButton = QtWidgets.QRadioButton(self.groupBox_4)
        self.holdOutRadioButton.setObjectName("holdOutRadioButton")
        self.gridLayout_5.addWidget(self.holdOutRadioButton, 3, 0, 1, 1)
        self.kFoldRadioButton = QtWidgets.QRadioButton(self.groupBox_4)
        self.kFoldRadioButton.setChecked(True)
        self.kFoldRadioButton.setObjectName("kFoldRadioButton")
        self.gridLayout_5.addWidget(self.kFoldRadioButton, 2, 0, 1, 1)
        self.kfoldsLabel = QtWidgets.QLabel(self.groupBox_4)
        self.kfoldsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.kfoldsLabel.setObjectName("kfoldsLabel")
        self.gridLayout_5.addWidget(self.kfoldsLabel, 2, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 2, 4, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 0, 0, 1, 4)
        self.validationPointsLabel = QtWidgets.QLabel(self.groupBox_4)
        self.validationPointsLabel.setEnabled(False)
        self.validationPointsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.validationPointsLabel.setObjectName("validationPointsLabel")
        self.gridLayout_5.addWidget(self.validationPointsLabel, 3, 3, 1, 1)
        self.kfoldsHorizontalSlider = QtWidgets.QSlider(self.groupBox_4)
        self.kfoldsHorizontalSlider.setMinimum(2)
        self.kfoldsHorizontalSlider.setMaximum(20)
        self.kfoldsHorizontalSlider.setProperty("value", 10)
        self.kfoldsHorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.kfoldsHorizontalSlider.setObjectName("kfoldsHorizontalSlider")
        self.gridLayout_5.addWidget(self.kfoldsHorizontalSlider, 2, 1, 1, 1)
        self.holdoutHorizontalSlider = QtWidgets.QSlider(self.groupBox_4)
        self.holdoutHorizontalSlider.setEnabled(False)
        self.holdoutHorizontalSlider.setMinimum(50)
        self.holdoutHorizontalSlider.setMaximum(90)
        self.holdoutHorizontalSlider.setProperty("value", 75)
        self.holdoutHorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.holdoutHorizontalSlider.setObjectName("holdoutHorizontalSlider")
        self.gridLayout_5.addWidget(self.holdoutHorizontalSlider, 3, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setEnabled(False)
        self.label_8.setToolTip("")
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 3, 4, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem5, 1, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_4, 3, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.regrComboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.regrComboBox.setObjectName("regrComboBox")
        self.regrComboBox.addItem("")
        self.regrComboBox.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.regrComboBox)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.corrComboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.corrComboBox.setObjectName("corrComboBox")
        self.corrComboBox.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.corrComboBox)
        self.gridLayout_3.addLayout(self.formLayout, 4, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem6, 5, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem7, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 2, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 0, 0, 1, 1)
        self.generateModelpushButton = QtWidgets.QPushButton(self.groupBox_3)
        self.generateModelpushButton.setObjectName("generateModelpushButton")
        self.gridLayout_4.addWidget(self.generateModelpushButton, 1, 0, 1, 1)
        self.viewPlotPushButton = QtWidgets.QPushButton(self.groupBox_3)
        self.viewPlotPushButton.setEnabled(False)
        self.viewPlotPushButton.setObjectName("viewPlotPushButton")
        self.gridLayout_4.addWidget(self.viewPlotPushButton, 1, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem8, 2, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_3, 5, 1, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.thetaTableView = QtWidgets.QTableView(self.groupBox_6)
        self.thetaTableView.setObjectName("thetaTableView")
        self.thetaTableView.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_7.addWidget(self.thetaTableView, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_7.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_6, 2, 0, 2, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.outvariableTableView = QtWidgets.QTableView(self.groupBox_5)
        self.outvariableTableView.setObjectName("outvariableTableView")
        self.outvariableTableView.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_6.addWidget(self.outvariableTableView, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_6.addWidget(self.label_7, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_5, 5, 0, 2, 1)
        self.confirmPushButton = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.confirmPushButton.sizePolicy().hasHeightForWidth())
        self.confirmPushButton.setSizePolicy(sizePolicy)
        self.confirmPushButton.setObjectName("confirmPushButton")
        self.gridLayout_2.addWidget(self.confirmPushButton, 12, 1, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem9, 12, 0, 1, 1)
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_7.setTitle("")
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.crossValMetricTableView = QtWidgets.QTableView(self.groupBox_7)
        self.crossValMetricTableView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.crossValMetricTableView.setObjectName("crossValMetricTableView")
        self.crossValMetricTableView.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_8.addWidget(self.crossValMetricTableView, 1, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_7)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_8.addWidget(self.label_10, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_7, 11, 0, 1, 2)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.kFoldRadioButton.toggled['bool'].connect(self.kfoldsHorizontalSlider.setEnabled)
        self.kFoldRadioButton.toggled['bool'].connect(self.kfoldsLabel.setEnabled)
        self.kFoldRadioButton.toggled['bool'].connect(self.label_9.setEnabled)
        self.holdOutRadioButton.toggled['bool'].connect(self.holdoutHorizontalSlider.setEnabled)
        self.holdOutRadioButton.toggled['bool'].connect(self.validationPointsLabel.setEnabled)
        self.holdOutRadioButton.toggled['bool'].connect(self.label_8.setEnabled)
        self.holdOutRadioButton.toggled['bool'].connect(self.viewPlotPushButton.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "Metamodel Construction"))
        self.holdOutRadioButton.setText(_translate("Dialog", "Hold out"))
        self.kFoldRadioButton.setText(_translate("Dialog", "K-Folds"))
        self.kfoldsLabel.setToolTip(_translate("Dialog", "Number of k folds to cross validate the model"))
        self.kfoldsLabel.setText(_translate("Dialog", "10"))
        self.label_9.setToolTip(_translate("Dialog", "Folds"))
        self.label_9.setText(_translate("Dialog", "Folds"))
        self.label_6.setText(_translate("Dialog", "Choose which type of validation to perform"))
        self.validationPointsLabel.setToolTip(_translate("Dialog", "This is the % of the points that are going to be used to build the model, the rest is going to be used as validation set."))
        self.validationPointsLabel.setText(_translate("Dialog", "75"))
        self.label_8.setText(_translate("Dialog", "% Training set"))
        self.label_4.setText(_translate("Dialog", "Regression and Correlation (Kernel) model selection"))
        self.label_2.setText(_translate("Dialog", "Polynomial (regression) model:"))
        self.regrComboBox.setItemText(0, _translate("Dialog", "Constant (0th order)"))
        self.regrComboBox.setItemText(1, _translate("Dialog", "Linear (1st order)"))
        self.label_3.setText(_translate("Dialog", "Correlation (kernel) model:"))
        self.corrComboBox.setItemText(0, _translate("Dialog", "Exponential Gaussian (Kriging)"))
        self.label_5.setText(_translate("Dialog", "Results generation and visualization"))
        self.generateModelpushButton.setText(_translate("Dialog", "Generate metamodel"))
        self.viewPlotPushButton.setText(_translate("Dialog", "View graphical results"))
        self.label.setText(_translate("Dialog", "Hyperparameters (theta) definition"))
        self.label_7.setText(_translate("Dialog", "Choose which variables will have their model built"))
        self.confirmPushButton.setText(_translate("Dialog", "OK"))
        self.label_10.setText(_translate("Dialog", "Validation metrics"))

